import { library as globalLibrary } from '@fortawesome/fontawesome-svg-core';
import { FaIconLibrary } from '@fortawesome/angular-fontawesome';
import {
    faArrowRight,
    faArrowUpRightFromSquare,
    faBars,
    faBriefcase,
    faChevronUp,
    faCode,
    faDatabase,
    faDragon,
    faFire,
    faGamepad,
    faGraduationCap,
    faLeaf,
    faPeopleGroup,
    faRotateRight,
    faScroll,
    faShieldHalved,
    faTrophy,
    faUsersGear,
    faXmark,
} from '@fortawesome/free-solid-svg-icons';
import { faEnvelope } from '@fortawesome/free-regular-svg-icons';
import {
    faAndroid,
    faAngular,
    faAws,
    faDocker,
    faFlutter,
    faGitAlt,
    faGithub,
    faGoogle,
    faJava,
    faLinkedinIn,
    faLinux,
    faNodeJs,
    faPython,
    faReact,
    faSass,
    faSwift,
    faUnity,
    faWhatsapp,
} from '@fortawesome/free-brands-svg-icons';

const icons = [
    faArrowRight,
    faArrowUpRightFromSquare,
    faBars,
    faBriefcase,
    faChevronUp,
    faCode,
    faDatabase,
    faDragon,
    faFire,
    faGamepad,
    faGraduationCap,
    faLeaf,
    faPeopleGroup,
    faRotateRight,
    faScroll,
    faShieldHalved,
    faTrophy,
    faUsersGear,
    faXmark,
    faEnvelope,
    faAndroid,
    faAngular,
    faAws,
    faDocker,
    faFlutter,
    faGitAlt,
    faGithub,
    faGoogle,
    faJava,
    faLinkedinIn,
    faLinux,
    faNodeJs,
    faPython,
    faReact,
    faSass,
    faSwift,
    faUnity,
    faWhatsapp,
];

export function registerIcons(library?: FaIconLibrary): void {
    if (library) library.addIcons(...icons);
    globalLibrary.add(...icons);
}
